config/routes.rb
Rails.application.routes.draw do
  get 'user/index' => 'user#index'
  get 'photo/index/:id' => 'photo#index', as: 'user_photos'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to  :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :photos
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController
  def index
    @user = User.find_by(id: params[:id])
    @photos = Photo.where(user_id: params[:id])
    @comments = Comment.all
    @user_all = User.all
  end

  def display_name(user_id)
    @user = User.find_by(id: user_id)
    return @user.first_name
  end
  helper_method :display_name
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users=User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photo/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photosite</title>
</head>

<body bgcolor="f08080">
<div style="color:#F7F7F7">
  <h1><center>Photosite</center></h1>
  <h3><center>User Photo Page</center></h3>
</div>
<div>
  <center>
    <h1>Photos of <%= @user.first_name %> <%= @user.last_name %></h1>
    <% @photos.each do |photo| %>
      <center>
        <%= image_tag("/assets/#{photo.file_name}") %>
        <p> Photo Created At   <%= photo.date_time %></p>
        <center>
          <% @comments.where("photo_id=?",photo.id).each do |comment| %>
            <li>
              <p> Comment: <%= comment.comment_text %></p>
              <p> Created at: <%= comment.date_time %></p>
              <p> Posted by: <%= link_to display_name(comment.user_id) , user_photos_path(comment.user_id) %></p>
            </li>
            </center>
          <% end %>
          </center>
      </ul>
      <br>
      </center>
      </div>
      <br>
    <%end%>

    </body>
</html>

app/views/user/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photo site</title>
</head>
<body bgcolor="#f08080">
<div style="color:#F7F7F7">
  <center>
    <h1 style="font-size: 300%;">PhotoSite</h1>
    <h3 style="font-size: 170%;"><i>Here's the user list. Select the Index to view further details of users!</i></h3>
  </center>
</div>
<div>
  <center>
    <table>
      <tr>
        <th style="font-size: 140%;"><h2>Index </h2></th>
        <th style="font-size: 140%;"><h2>First </h2></th>
        <th style="font-size: 140%;"><h2>Last </h2></th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <th style="font-size: 120%;"><%= link_to user.id, user_photos_path(user.id) %></th>
          <td style="font-size: 120%;"><%= user.first_name %></td>
          <td style="font-size: 120%;"><%= user.last_name %></td>
        </tr>
      <% end %>
    </table>
  </center>
</div>
</body>
</html>